### ISSUE TITLE
Compiling lact-gui failed

### ISSUE THREAD

**Issue by krasseboehmer** [ilya-zlobintsev/LACT#342]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

While compiling the lact-gui package failes

```
Compiling lact-gui v0.5.4 (/var/tmp/pamac-build-xyz/lact/src/LACT/lact-gui)
Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
   --> lact-gui/src/app/graphs_window/mod.rs:122:14
    |
122 |     #[derive(CompositeTemplate, Default)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: called 'Result::unwrap()' on an 'Err' value: 
            
            Stack backtrace:
               0: <unknown>
               1: <unknown>
               2: <unknown>
               3: <unknown>
               4: <unknown>
               5: <unknown>
               6: <unknown>
               7: <unknown>
               8: <unknown>
               9: <unknown>
              10: <unknown>
              11: <unknown>
              12: <unknown>
              13: <unknown>
              14: <unknown>
              15: <unknown>
              16: <unknown>
              17: <unknown>
              18: <unknown>
              19: <unknown>
              20: <unknown>
              21: <unknown>
              22: <unknown>
              23: <unknown>
              24: <unknown>
              25: <unknown>
              26: <unknown>
              27: <unknown>
              28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
              29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
              30: <rustc_expand::expand::MacroExpander>::expand_crate
              31: <unknown>
              32: <unknown>
              33: <unknown>
              34: <unknown>
              35: <unknown>
              36: <unknown>
              37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
              38: <unknown>
              39: <unknown>
              40: <unknown>
              41: <unknown>
              42: <unknown>
              43: <unknown>
              44: <unknown>
              45: <unknown>
    = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/info_row.rs:32:14
   |
32 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/page_section.rs:37:14
   |
37 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
   --> lact-gui/src/app/root_stack/info_page/hardware_info.rs:147:14
    |
147 |     #[derive(CompositeTemplate, Default, Properties)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: called 'Result::unwrap()' on an 'Err' value: 
            
            Stack backtrace:
               0: <unknown>
               1: <unknown>
               2: <unknown>
               3: <unknown>
               4: <unknown>
               5: <unknown>
               6: <unknown>
               7: <unknown>
               8: <unknown>
               9: <unknown>
              10: <unknown>
              11: <unknown>
              12: <unknown>
              13: <unknown>
              14: <unknown>
              15: <unknown>
              16: <unknown>
              17: <unknown>
              18: <unknown>
              19: <unknown>
              20: <unknown>
              21: <unknown>
              22: <unknown>
              23: <unknown>
              24: <unknown>
              25: <unknown>
              26: <unknown>
              27: <unknown>
              28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
              29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
              30: <rustc_expand::expand::MacroExpander>::expand_crate
              31: <unknown>
              32: <unknown>
              33: <unknown>
              34: <unknown>
              35: <unknown>
              36: <unknown>
              37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
              38: <unknown>
              39: <unknown>
              40: <unknown>
              41: <unknown>
              42: <unknown>
              43: <unknown>
              44: <unknown>
              45: <unknown>
    = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/info_page/vulkan_info/feature_window/row.rs:31:14
   |
31 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/info_page/vulkan_info/feature_window/mod.rs:38:14
   |
38 |     #[derive(CompositeTemplate, Properties, Default)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
   --> lact-gui/src/app/root_stack/oc_page/gpu_stats_section.rs:104:14
    |
104 |     #[derive(CompositeTemplate, Default, Properties)]
    |              ^^^^^^^^^^^^^^^^^
    |
    = help: message: called 'Result::unwrap()' on an 'Err' value: 
            
            Stack backtrace:
               0: <unknown>
               1: <unknown>
               2: <unknown>
               3: <unknown>
               4: <unknown>
               5: <unknown>
               6: <unknown>
               7: <unknown>
               8: <unknown>
               9: <unknown>
              10: <unknown>
              11: <unknown>
              12: <unknown>
              13: <unknown>
              14: <unknown>
              15: <unknown>
              16: <unknown>
              17: <unknown>
              18: <unknown>
              19: <unknown>
              20: <unknown>
              21: <unknown>
              22: <unknown>
              23: <unknown>
              24: <unknown>
              25: <unknown>
              26: <unknown>
              27: <unknown>
              28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
              29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
              30: <rustc_expand::expand::MacroExpander>::expand_crate
              31: <unknown>
              32: <unknown>
              33: <unknown>
              34: <unknown>
              35: <unknown>
              36: <unknown>
              37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
              38: <unknown>
              39: <unknown>
              40: <unknown>
              41: <unknown>
              42: <unknown>
              43: <unknown>
              44: <unknown>
              45: <unknown>
    = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_cap_section.rs:44:14
   |
44 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_states/power_state_row.rs:37:14
   |
37 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_states/power_states_frame.rs:81:14
   |
81 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/oc_page/power_states/power_states_list.rs:99:14
   |
99 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
error: proc macro panicked
  --> lact-gui/src/app/root_stack/software_page.rs:52:14
   |
52 |     #[derive(CompositeTemplate, Default, Properties)]
   |              ^^^^^^^^^^^^^^^^^
   |
   = help: message: called 'Result::unwrap()' on an 'Err' value: 
           
           Stack backtrace:
              0: <unknown>
              1: <unknown>
              2: <unknown>
              3: <unknown>
              4: <unknown>
              5: <unknown>
              6: <unknown>
              7: <unknown>
              8: <unknown>
              9: <unknown>
             10: <unknown>
             11: <unknown>
             12: <unknown>
             13: <unknown>
             14: <unknown>
             15: <unknown>
             16: <unknown>
             17: <unknown>
             18: <unknown>
             19: <unknown>
             20: <unknown>
             21: <unknown>
             22: <unknown>
             23: <unknown>
             24: <unknown>
             25: <unknown>
             26: <unknown>
             27: <unknown>
             28: <rustc_expand::proc_macro::BangProcMacro as rustc_expand::base::BangProcMacro>::expand
             29: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
             30: <rustc_expand::expand::MacroExpander>::expand_crate
             31: <unknown>
             32: <unknown>
             33: <unknown>
             34: <unknown>
             35: <unknown>
             36: <unknown>
             37: <rustc_middle::ty::context::TyCtxt>::resolver_for_lowering
             38: <unknown>
             39: <unknown>
             40: <unknown>
             41: <unknown>
             42: <unknown>
             43: <unknown>
             44: <unknown>
             45: <unknown>
   = note: this error originates in the derive macro 'CompositeTemplate' (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile 'lact-gui' (lib) due to 12 previous errors
==> ERROR: A failure occurred in build().
    Aborting...
```

### System info

```markdown
- LACT version: 5.4-2
- GPU model: RX 7900 XT
- Kernel version: 6.9.3-3-MANJARO
- Distribution: MANJARO (Gnome Version)
```

**Comment by ilya-zlobintsev** [comment]
You have a non-functional installation of `blueprint-compiler`, related to some python packaging error:
```
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
```
There was a similar error reported in the AUR with a link to this report, maybe it helps: https://bugs.archlinux.org/task/78484

**Comment by krasseboehmer** [comment]
Thanks, I fixed it by renaming the `usr/local/bin/python3` to `usr/local/bin/python3cust`.

turned out my python3 was pointing to the 3.10 version and after this it fell back to 3.12.
